name: Publish Github Pages

on:
  push:
    branches:
      - add_tck_tests

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build tck runner reports
      run: make
      working-directory: ./runner
    - name: Create .nojekyll file
      run: touch runner/reports/html/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: runner/reports/html/ # The folder the action should deploy.
